### ISSUE TITLE
Remove some TODO comments

### ISSUE THREAD

**Issue by PatrickKa** [SpaceTeam/STS1_COBC_SW#269]
### Description

The following `TODO` comments are outdated or otherwise unnecessary and should be removed:

- [x] Sts1CobcSw/CMakeLists.txt: lines 1-2
- [x] Sts1CobcSw/Periphery/Flash.cpp: line 223
- [x] Sts1CobcSw/FileSystem/FileSystem.cpp: line 41
