### ISSUE TITLE
Add fallback mechanisms for SPI peripherals

### ISSUE THREAD

**Issue by PatrickKa** [SpaceTeam/STS1_COBC_SW#294]
### Description

We have startup checks to see if the SPI peripherals (FRAM, EPS, Flash, and RF) are working. If there is a problem with any of those, except for the RF module, we still want to run our SW. Therefore, we need to check if a peripheral is working before we use it and, in case it isn't, have some fallback implementation that gets executed instead.

Fallback mechanisms for SPI peripherals:

- [x] **RF**: We are pretty much dead, so the only thing we can do is reboot, maybe with a little delay. This is covered by #268.
- [x] **FRAM**: Persistent State and Telemetry Memory is stored in RAM instead. The size of the Telemetry Memory will be drastically reduced to save memory. The sizes of the EDU queue and status history will also be decreased. To implement this, the persistent variables, EDU program queue, EDU program status history, and Telemetry Memory should all have an internal "cache" that is always used to store the data written to the FRAM. If the FRAM fails, the values are then also read from this "cache" instead. Since nothing that builds on top of the FRAM is implemented, yet we can do it right the first time, meaning that this is covered in #202, #203, and #323.
- [x] **Flash**: We cannot implement the COBC file system in RAM or anywhere else, so we basically cannot use it. Without it, it makes no sense to execute EDU programs, so this also disables the EDU (I already added a check in the EDU power management thread for this on miro, so this is covered with #53). We still need to provide some fallback mechanism/implementation for the file system, though, because the GS can still send file system commands. This is covered in #363.
- [x] **EPS**: #295
